App_AssMat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('liste_employeurs/', include('famille.urls')),
    path('liste_contrats/', include('contrat.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/contrat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from contrat.views import (ContratView,
                           ContratCreate,
                           EnfantView,
                           RemunerationView,
                           CongePayeView,
                           EnfantCreate,
                           EnfantDetail,
                           EnfantUpdateView,
                           EnfantDeleteView,
                           
                           )

app_name = "contrat"

urlpatterns = [
    path('', ContratView.as_view() , name='liste_contrats'),
    path('creation_contrat/', ContratCreate.as_view() , name='creation_contrats'),
    path('creation_enfants/', EnfantCreate.as_view() , name='creation_enfants'),
    path('<int:pk>/', EnfantDetail.as_view(), name='details_enfants'),
    path('<int:pk>/edit/', EnfantUpdateView.as_view(), name='editter_enfants'),
    path('<int:pk>/delete/', EnfantDeleteView.as_view(), name='effacer_enfants'),
    path('liste_enfants/', EnfantView.as_view() , name='liste_enfants'),
    path('liste_remunerations/', RemunerationView.as_view(), name='liste_remunerations'),
    path('liste_congepayer/', CongePayeView.as_view() , name='liste_congepayer'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/dashboard/urls.py
from django.urls import path
from django.urls.conf import include, include
from dashboard.views import index, Contrat_Vierge
from django.conf import settings
from django.conf.urls.static import static


app_name = 'dashboard'

urlpatterns = [
    path('', index, name='dashboard'),
    path('contrat_vierge/', Contrat_Vierge , name='contrat_vierge'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/famille/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from famille.views import (EmployeurView, 
                           EmployeurCreate, 
                           EmployeurDetail, 
                           EmployeurDeleteView, 
                           EmployeurUpdateView,
                           ContactUrgenceCreate,
                           ContactUrgenceView,
                           ContactUrgenceDetail,
                           ContactUrgenceUpdateView,
                           ContactUrgenceDeleteView,
                           )


# Create your views here.
app_name = 'famille'

urlpatterns = [
    path('', EmployeurView.as_view(), name='liste_employeurs'),
    path('creation_employeur/', EmployeurCreate.as_view(), name='creation_employeur'),
    path('<int:pk>/', EmployeurDetail.as_view(), name='details_employeur'),
    path('<int:pk>/edit/', EmployeurUpdateView.as_view(), name='editter_employeur'),
    path('<int:pk>/delete/', EmployeurDeleteView.as_view(), name='effacer_employeur'),
    path('<int:pk>/liste_contact_urgence/', ContactUrgenceView.as_view(), name='liste_contact_urgence'),
    path('<int:pk>/creation_contact_urgence/', ContactUrgenceCreate.as_view(), name='creation_contact_urgence'),
    # path('<int:pk>/liste_contact_urgence/<int:pk>/detail_urgence/', ContactUrgenceDetail.as_view(), name='detail_urgence'),
    path('liste_contact_urgence/<int:pk>/edit/', ContactUrgenceUpdateView.as_view(), name='edit_urgence'),
    path('liste_contact_urgence/<int:pk>/delete/', ContactUrgenceDeleteView.as_view(), name='effacer_urgence'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/dashboard/models.py
from django.db import models

# Create your models here.

App_AssMat/dashboard/views.py
from django.shortcuts import render
from famille.models import Employeur
from contrat.models import (Contrat, 
                            Enfant, 
                            Remuneration, 
                            CongePaye,
                            )


# Create your views here.
def index(request):
    """ """
    employeurs = Employeur.objects.all()
    contrats = Contrat.objects.all()
    enfants = Enfant.objects.all()
    remunerations = Remuneration.objects.all()
    conges = CongePaye.objects.all()
    context = {"employeurs":employeurs,
               "contrats":contrats,
               "enfants":enfants,
               "remunerations":remunerations,
               "conges":conges,
               }
    
    return render(request, "dashboard/base_dashboard.html", context)


def Contrat_Vierge(request):
    """"""
    return render(request, "dashboard/contrat_vierge.html")

App_AssMat/dashboard/templates/dashboard/base_dashboard.html
<!DOCTYPE html>
{% load static %}
<html lang="en"></html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super_AssMat</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <!-- Bulma Version 0.9.0-->
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
    <link rel="stylesheet" type="text/css" href="../css/admin.css">
</head>

<body>

    <!-- START NAV -->
    <nav class="navbar is-white"></nav>
    <!-- END NAV -->
    <div class="container">
        <div class="columns">
            <div class="column is-2 ">
                <aside class="menu is-hidden-mobile">
                    <p class="menu-label">
                        General
                    </p>
                    <ul class="menu-list">
                        <li><a class="navbar-item" href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
                        <li><a class="navbar-item" href="{% url 'contrat:liste_contrats' %}">Contrats</a></li>
                        <li><a class="navbar-item" href="{% url 'dashboard:dashboard' %}">Profils</a></li>
                        <li><a class="navbar-item" href="{% url 'famille:creation_employeur' %}">Ajouter employeur</a></li>
                        <li><a class="navbar-item" href="{% url 'contrat:creation_enfants' %}">Ajouter enfant</a></li>
                        <li><a>se connecter</a></li>
                        <li><a>se deconnecter</a></li>
                    </ul>
                    <p class="menu-label">
                        Recapitulatifs
                    </p>
                    <ul class="menu-list">
                        <li><a href="{% url 'dashboard:contrat_vierge' %}">Exemple contrat vierge </a></li>
                        <li><a href="{% url 'contrat:liste_contrats' %}">Liste des contrats</a></li>
                        <li><a href="{% url 'contrat:liste_enfants' %}">Liste des enfants</a></li>
                        
                    </ul>
                    <p class="menu-label">
                        Salaire
                    </p>
                    <ul class="menu-list">
                        <li><a>Fiche de paie</a></li>
                        <li><a>Congé</a></li>
                        <li><a>Recap semaine</a></li>
                        <li><a>Recap mois</a></li>
                        <li><a>Recap année</a></li>
                    </ul>
                    <p class="menu-label">
                        <a href="{% url 'famille:liste_employeurs'%}">Recap famille</a>
                    </p>
                    <ul class="menu-list">
                        {% for employeur in employeurs %}
                        <li><a href="{% url 'famille:details_employeur' pk=employeur.id %}">{{ employeur.nom }}</a></li>
                        {% endfor %}
                    </ul>
                    <p class="menu-label">
                        Recap enfant
                    </p>
                    <ul class="menu-list">
                        {% for enfant in enfants %}
                        <li><a href="#">{{ enfant.nom }}</a></li>
                        {% endfor %}
                    </ul>    
                </aside>
            </div>
            <div class="column">
                <section class="hero is-info welcome is-small">
                    <div class="hero-body">
                        <div class="container">
                            <h1 class="title">
                                Bonjour {{user.username}}
                            </h1>
                            <h2 class="subtitle">
                                Bienvenue sur votre tableau de bord!
                            </h2>
                        </div>
                    </div>
                </section>
                <section class="info-tiles">
                    <div class="tile is-ancestor has-text-centered">
                        <div class="tile is-parent">
                            <article class="tile is-child box">
                                <p class="title">????voir methode de class attribut de classe?</p>
                                <p class="subtitle">nombre d'enfants</p>
                            </article>
                        </div>
                        <div class="tile is-parent">
                            <article class="tile is-child box">
                                <p class="title">???? voir methode de class attribut de classe?</p>
                                <p class="subtitle">nombre de contrats</p>
                            </article>
                        </div>
                        <div class="tile is-parent">
                            <article class="tile is-child box">
                                <p class="title">????</p>
                                <p class="subtitle">autres truc</p>
                            </article>
                        </div>
                        <div class="tile is-parent">
                            <article class="tile is-child box">
                                <p class="title">?????</p>
                                <p class="subtitle">nombre de jours sans enfants morts</p>
                            </article>
                        </div>
                    </div>
                </section>
                <br>
                {% include "contrat/enfant_list.html" %}
                <br>     
                  
                
            </div>
        </div>
    </div> 

    
    <footer class="footer">
        <div class="content has-text-centered">
          <p>
            <strong>AssMat</strong> by <a href="">moi</a>
            <a href="">!!!!</a> The website  <a href="">au top</a>.
          </p>
        </div>
    </footer>
  </body>

</html>

App_AssMat/dashboard/templates/dashboard/base_dashboard_02.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Super_AssMat</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
        <!-- Bulma Version 0.9.0-->
        <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
        <link rel="stylesheet" type="text/css" href="../css/admin.css">
    </head>
    
    <body>
    
        <!-- START NAV -->
        <nav class="navbar is-white"></nav>
        <!-- END NAV -->
        <div class="container">
            <div class="columns">
                <div class="column is-2 ">
                    <aside class="menu is-hidden-mobile">
                        <p class="menu-label">
                            General
                        </p>
                        <ul class="menu-list">
                            <li><a class="navbar-item" href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
                            <li><a class="navbar-item" href="{% url 'contrat:liste_contrats' %}">Contrats</a></li>
                            <li><a class="navbar-item" href="{% url 'dashboard:dashboard' %}">Profils</a></li>
                            <li><a class="navbar-item" href="{% url 'famille:creation_employeur' %}">Ajouter employeur</a></li>
                            <li><a>se connecter</a></li>
                            <li><a>se deconnecter</a></li>
                        </ul>
                        <p class="menu-label">
                            Recapitulatifs
                        </p>
                        <ul class="menu-list">
                            <li><a href="{% url 'dashboard:contrat_vierge' %}">Exemple contrat vierge </a></li>
                            <li><a href="{% url 'contrat:liste_contrats' %}">Liste des contrats</a></li>
                            <li><a href="{% url 'contrat:liste_enfants' %}">Liste des enfants</a></li>
                            
                        </ul>
                        <p class="menu-label">
                            Salaire
                        </p>
                        <ul class="menu-list">
                            <li><a>Fiche de paie</a></li>
                            <li><a>Congé</a></li>
                            <li><a>Recap semaine</a></li>
                            <li><a>Recap mois</a></li>
                            <li><a>Recap année</a></li>
                        </ul>
                        <p class="menu-label">
                            <a href="{% url 'famille:liste_employeurs'%}">Recap famille</a>
                        </p>
                        <ul class="menu-list">
                            {% for employeur in employeurs %}
                            <li><a href="{% url 'famille:details_employeur' pk=employeur.id %}">{{ employeur.nom }}</a></li>
                            {% endfor %}
                        </ul>
                        <p class="menu-label">
                            Recap enfant
                        </p>
                        <ul class="menu-list">
                            
                            <li><a href="#">{{ enfant.nom }}</a></li>
                            
                        </ul>
                        
                    </aside>
                </div>
                <div class="column">
                    <section class="hero is-info welcome is-small">
                        <div class="hero-body">
                            <div class="container">
                                <h1 class="title">
                                    Bonjour {{user.username}}
                                </h1>
                                <h2 class="subtitle">
                                    Bienvenue sur votre tableau de bord!
                                </h2>
                            </div>
                        </div>
                    </section>
                    <section class="info-tiles">
                        <div class="tile is-ancestor has-text-centered">
                            <div class="tile is-parent">
                                <article class="tile is-child box">
                                    <p class="title">????voir methode de class attribut de classe?</p>
                                    <p class="subtitle">nombre d'enfants</p>
                                </article>
                            </div>
                            <div class="tile is-parent">
                                <article class="tile is-child box">
                                    <p class="title">???? voir methode de class attribut de classe?</p>
                                    <p class="subtitle">nombre de contrats</p>
                                </article>
                            </div>
                            <div class="tile is-parent">
                                <article class="tile is-child box">
                                    <p class="title">????</p>
                                    <p class="subtitle">autres truc</p>
                                </article>
                            </div>
                            <div class="tile is-parent">
                                <article class="tile is-child box">
                                    <p class="title">?????</p>
                                    <p class="subtitle">nombre de jours sans enfants morts</p>
                                </article>
                            </div>
                        </div>
                    </section>
                    <br>
                    <div class="card events-card">
                    {% block content %}
    
                    {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="content has-text-centered">
            <p>
                <strong>AssMat</strong> by <a href="">moi</a>
                <a href="">!!!!</a> The website  <a href="">au top</a>.
            </p>
            </div>
        </footer>
    </body>
</html>