App_AssMat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('liste_employeurs/', include('famille.urls')),
    path('liste_contrats/', include('contrat.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/contrat/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from contrat.views import (ContratView,
                           ContratCreate,
                           EnfantView,
                           RemunerationView,
                           CongePayeView,
                           EnfantCreate,
                           EnfantDetail,
                           EnfantUpdateView,
                           EnfantDeleteView,
                           
                           )

app_name = "contrat"

urlpatterns = [
    path('', ContratView.as_view() , name='liste_contrats'),
    path('creation_contrat/', ContratCreate.as_view() , name='creation_contrats'),
    path('creation_enfants/', EnfantCreate.as_view() , name='creation_enfants'),
    path('<int:pk>/', EnfantDetail.as_view(), name='details_enfants'),
    path('<int:pk>/edit/', EnfantUpdateView.as_view(), name='editter_enfants'),
    path('<int:pk>/delete/', EnfantDeleteView.as_view(), name='effacer_enfants'),
    path('liste_enfants/', EnfantView.as_view() , name='liste_enfants'),
    path('liste_remunerations/', RemunerationView.as_view(), name='liste_remunerations'),
    path('liste_congepayer/', CongePayeView.as_view() , name='liste_congepayer'),
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/dashboard/urls.py
from django.urls import path
from django.urls.conf import include, include
from dashboard.views import index, Contrat_Vierge
from django.conf import settings
from django.conf.urls.static import static


app_name = 'dashboard'

urlpatterns = [
    path('', index, name='dashboard'),
    path('contrat_vierge/', Contrat_Vierge , name='contrat_vierge'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/contrat/models.py
from django.db import models

from famille.models import Employeur

# Create your models here.
class TypeContrat(models.Model):
    
    choix_titre = [('cdi', 'Cdi'),
                     ('cdd', 'Cdd'),
                     ('occasionnel', 'Occasionnel')]
    
    titre = models.CharField(max_length=50, choices=choix_titre)
    
    class Meta:
        verbose_name = "Titre"
        verbose_name_plural = "Titres"
    
    def __str__(self):
        return f"{self.titre}"


class Contrat(models.Model):
    nom = models.CharField(max_length=40, blank=True, null=True)
    date_creation = models.DateTimeField(auto_now_add=True)
    date_debut = models.DateTimeField(blank=True, null=True)
    date_fin = models.DateTimeField(blank=True, null=True)
    heure_hebdo = models.IntegerField(blank=True, null=True)
    jour_hebdo = models.IntegerField(blank=True, null=True)
    nb_semaine = models.IntegerField(blank=True, null=True)
    date_paiement = models.DateTimeField(blank=True, null=True)
    type_contrat = models.ForeignKey(to=TypeContrat, on_delete=models.CASCADE)
    employeur = models.ForeignKey(to=Employeur, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Contrat"
        verbose_name_plural = "Contrats"

    def __str__(self):
        return f"{self.nom} - {self.employeur}"


class Enfant(models.Model):
    photo = models.ImageField(upload_to="photo_profil/", blank=True, null=True)
    nom = models.CharField(max_length=40, blank=True, null=True)
    prenom = models.CharField(max_length=20, blank=True, null=True)
    date_anniv = models.DateTimeField(blank=True, null=True)
    age = models.PositiveIntegerField(blank=True, null=True)
    commentaire = models.TextField(blank=True, null=True)
    contrat = models.ForeignKey(to=Contrat, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Enfant"
        verbose_name_plural = "Enfants"

    def __str__(self):
        return f"{self.nom} - {self.prenom}"
    
        
class Remuneration(models.Model):
    base_mensuel = models.FloatField(blank=True, null=True)
    heure_mensuel = models.FloatField(blank=True, null=True)
    taux_h_brut = models.FloatField(blank=True, null=True)
    taux_h_net = models.FloatField(blank=True, null=True)
    jour_mensuel = models.FloatField(blank=True, null=True)
    contrat = models.ForeignKey(to=Contrat, on_delete=models.CASCADE)
    
    
    class Meta:
        verbose_name = "Remuneration"
        verbose_name_plural = "Remunerations"

    def __str__(self):
        return f"{self.contrat}"
    

class CongePaye(models.Model):
    maintient_salaire = models.FloatField(blank=True, null=True)
    dix_pourcent = models.FloatField(blank=True, null=True)
    
    class Meta:
        verbose_name = "Congé Payé"
        verbose_name_plural = "Congés Payés"

    def __str__(self):
        return f"{self.maintient_salaire} - {self.dix_pourcent}"

App_AssMat/contrat/forms.py
from django import forms
from contrat.models import Contrat, Enfant

class NewContratForm(forms.ModelForm):
    """"""
    class Meta:
        model = Contrat
        fields = [
            'nom',
            'date_debut',
            'date_fin',
            'heure_hebdo',
            'jour_hebdo',
            'nb_semaine',
            'date_paiement',
            'type_contrat',
            'employeur'
            
        ]


class NewEnfantForm(forms.ModelForm):
    """ from for the child creation """
    class Meta:
        model = Enfant
        fields = [
            'photo',
            'nom',
            'prenom',
            'date_anniv',
            'age',
            'commentaire',
            'contrat',
            
        ]

App_AssMat/contrat/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from contrat.models import Contrat, Enfant, Remuneration, CongePaye
from famille.models import Employeur, ContactUrgence
from contrat.forms import NewContratForm, NewEnfantForm

# Liste

class ContratView(ListView):
    model = Contrat
    context_object_name = 'contrats'
    template_name = 'contrat/contrat_list.html'


class EnfantView(ListView):
    model = Enfant
    context_object_name = 'enfants'
    template_name = 'contrat/enfant_list.html'


class RemunerationView(ListView):
    model = Remuneration
    context_object_name = 'remunerations'
    template_name = 'contrat/remuneration_list.html'

    
class CongePayeView(ListView):
    model = CongePaye
    context_object_name = 'conges'
    template_name = 'contrat/conge_list.html'
    
# Create   
class ContratCreate(CreateView):
    model = Contrat
    form_class = NewContratForm
    template_name = 'contrat/contrat_create.html'
    success_url = '/dashboard/'


class EnfantCreate(CreateView):
    model = Enfant
    form_class = NewEnfantForm
    template_name = 'contrat/enfant_create.html'
    success_url = '/dashboard/'
    
# details
class EnfantDetail(DetailView):
    model = Enfant
    context_object_name = "enfant"
    template_name = 'contrat/enfant_details.html'
    success_url = '/dashboard/'
    
    def get_context_data(self, **kwargs):
        context = {}
        enfant = Enfant.objects.get(id=self.kwargs["pk"])
        contrat = Contrat.objects.get(id=enfant.contrat.id)
        employeur = Employeur.objects.get(id=contrat.id)
        contacts_urgences = ContactUrgence.objects.filter(employeur=employeur)
        context['contacts_urgences'] = contacts_urgences
        return super().get_context_data(**context) # get the default context data
        
    
# Update
class EnfantUpdateView(UpdateView):
    model = Enfant
    form_class = NewEnfantForm
    context_object_name = "enfants"
    template_name = 'contrat/enfant_create.html'
    success_url = '/dashboard/'

# Delete 
class EnfantDeleteView(DeleteView):
    model = Enfant
    context_object_name = "enfants"
    template_name = 'contrat/enfant_delete.html'
    success_url = '/dashboard/'

App_AssMat/contrat/templates/contrat/conge_list.html
{% load static %}


<section class="section is-medium">
  <h1 class="title">Recap Conges payé</h1>
        <h2 class="subtitle">
          Recapitule tout <strong>les sales gosses que tu garde.</strong>
        </h2>

        <table class="table is-bordered">
      
            <thead>
                <tr>
                    <th>maintient_salaire</th>
                    <th>dix_pourcent</th>
                    <th>Modifier congés</th>
                </tr>
            </thead>
            <tbody>
              {% for conge in conges %}
              <tr>
                <th>{{ conge.maintient_salaire }}</th>
                <td>{{ conge.dix_pourcent }}</td>
                <td><a class="button is-dark" href="" >Modifier congés</a> </td> 
              </tr>
              {% endfor %}
            </tbody>
        </table>
</section>

App_AssMat/contrat/templates/contrat/contrat_create.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}
<form action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
                {{form.nom}}
            </div>
            <label class="label">Date de debut du contrat:</label>
            <div class="control">
                {{form.date_debut}}
            </div>
            <label class="label">Date de fin du contrat:</label>
            <div class="control">
                {{form.date_fin}}
            </div>
            <label class="label">Nombre d'heures hebdomadaire:</label>
            <div class="control">
                {{form.heure_hebdo}}
            </div>
            <label class="label">Nombre de jours hebdomadaire:</label>
            <div class="control">
                {{form.jour_hebdo}}
            </div>
            <label class="label">Nombre de semaines:</label>
            <div class="control">
                {{form.nb_semaine}}
            </div>
            <label class="label">Date de paiement:</label>
            <div class="control">
                {{form.date_paiement}}
            </div>
            <label class="label">Type de contrat:</label>
            <div class="control">
                {{form.type_contrat}}
            </div>
            <label class="label">Nom employeur:</label>
            <div class="control">
                {{form.employeur}}
            </div>
        </div>
    <input class="button is-dark" type="submit" value="Validez votre employeur"> 
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>          
</form>
{% endblock %}

App_AssMat/contrat/templates/contrat/contrat_list.html
{% load static %}


<section class="section is-medium">
  <h1 class="title">Recap Contrats</h1>
        <h2 class="subtitle">
          recapitule tout les <strong>Contrats</strong> dont tu garde les sales gosses.
        </h2>
        
        <a class="button is-dark" href="{% url 'contrat:creation_contrats' %}">Creation d'un nouveau contrat</a>
        
  <table class="table is-bordered">
      
      <thead>
          <tr>
              <th>ID</th>
              <th>nom</th>
              <th>date de création</th>
              <th>date de debut</th>
              <th>date de fin</th>
              <th>heure hebdomadaire</th>
              <th>jour hebdomadaire</th>
              <th>nombre de semaine</th>
              <th>date de paiement</th>
              <th>type de contrat</th>
              <th>employeur</th>
              <th>Modifier contrat</th>
          </tr>
      </thead>
      <tbody>
        {% for contrat in contrats %}
        <tr>
          <th>{{ contrat.id }}</th>
          <td><a href="" >{{ contrat.nom }}</a>
          </td>
          <td>{{ contrat.date_creation }}</td>
          <td>{{ contrat.date_debut }}</td>
          <td>{{ contrat.date_fin }}</td>
          <td>{{ contrat.heure_hebdo }} h</td>
          <td>{{ contrat.jour_hebdo }}</td>
          <td>{{ contrat.nb_semaine}}</td>
          <td>{{ contrat.date_paiement }}</td>
          <td>{{ contrat.type_contrat}}</td>
          <td>{{ contrat.employeur}}</td>
          <td><a class="button is-dark" href="" >Modifier contrat</a> </td> 
        </tr>
        {% endfor %}
      </tbody>
  </table>
</section>

App_AssMat/contrat/templates/contrat/enfant_create.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}
<form enctype="multipart/form-data" action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
                {{form.nom}}
            </div>
            <label class="label">Prénom:</label>
            <div class="control">
                {{form.prenom}}
            </div>
            <label class="label">Photo:</label>
            <div class="control">
                {{form.photo}}
            </div>
            <label class="label">Date d'anniversaire:</label>
            <div class="control">
                {{form.date_anniv}}
            </div>
            <label class="label">Age:</label>
            <div class="control">
                {{form.age}}
            </div>
            <label class="label">Commentaire:</label>
            <div class="control">
                {{form.commentaire}}
            </div>
            <label class="label">Contrat:</label>
            <div class="control">
                {{form.contrat}}
            </div>
            
            
        </div>
    <input class="button is-dark" type="submit" value="Validez votre enfant"> 
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>          
</form>
{% endblock %}

App_AssMat/contrat/templates/contrat/enfant_delete.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}

<form action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
               <p>Voulez-vous supprimer cet enfant: {{ enfant.nom }} ? </p> 
            </div>
        </div>
    <input class="button is-dark" type="submit" value="Validez votre suppression d'enfant">     
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>      
</form>
{% endblock %}

App_AssMat/contrat/templates/contrat/enfant_details.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}



{% block content %}
<div class="columns">
    <div class="column is-one-fifth">
        <figure class="image is-128x128">
            {% if enfant.photo %}
              <img src="{{ enfant.photo.url }}" alt="Image">
            {% endif %}
          </figure>  
    </div>
    <div class="column">
        <div class="field ">
            <label class="label">Nom:</label>
                <div class="control">
                    {{enfant.nom}}
                </div>
            <label class="label">Prénom:</label>
                <div class="control">
                    {{enfant.prenom}}
                </div>
            <label class="label">Photo:</label>
                <div class="control">
                    {{enfant.photo}}
                </div>
            <label class="label">Date d'anniversaire:</label>
                <div class="control">
                    {{enfant.date_anniv}}
                </div>
            <label class="label">Age:</label>
                <div class="control">
                    {{enfant.age}}
                </div>
            <label class="label">Commentaire:</label>
                <div class="control">
                    {{enfant.commentaire}}
                </div>
            <label class="label">Contrat:</label>
                <div class="control">
                    {{enfant.contrat}}
                </div>
            <br>
            
                
        </div>
        
    </div>
    <div class="column">
        <a class="button is-dark" href="{% url 'contrat:editter_enfants' pk=enfant.id %}" >Modifier enfant</a>
        <br><br>
        <a class="button is-dark" href="{% url 'contrat:effacer_enfants' pk=enfant.id %}" >Effacer enfant</a>
        <br><br>  
        <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>
    </div>
     
</div> 
<div class="column">
    {% include "famille/urgence_list.html" %}
</div>     
  
    
{% endblock %}

App_AssMat/contrat/templates/contrat/enfant_list.html
{% load static %}

<div class="card events-card">
  <header class="card-header">
    <p class="card-header-title">
      Récapitulatif informations enfants
    </p>
    <a href="#" class="card-header-icon" aria-label="more options"> </a>
  </header>
    
  <div class="card-table">  
    <div class="content">
      <div id="app" class="row columns">
        <div v-for="card in cardData" key="card.id" class="column is-4">
          <div class="card large">
            {% for enfant in enfants %}
            <div class="card-image">
              <figure class="image is-16by9">
                {% if enfant.photo %}
                  <img src="{{ enfant.photo.url }}" alt="Image">
                {% endif %}
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    {% if enfant.photo %}
                      <img src="{{ enfant.photo.url }}" alt="Image">
                    {% endif %}
                  </figure>
                </div>
                <div class="media-content">  
                        <p class="title is-4 no-padding">{{ enfant.nom }}</p>
                        <p>
                          <span class="title is-6">
                            <a > {{ enfant.prenom }} </a> </span> </p>
                        <p class="subtitle is-6">{{ enfant.date_anniv  }}</p>
                </div>
              </div>
                    <div class="content">
                      {{ enfant.age }} an(s)  / {{ enfant.contrat.employeur.nom }} / {{ enfant.contrat.nom }} 
                    </div>
                    <div>
                    <a class="button is-small is-primary" href="{% url 'contrat:details_enfants' pk=enfant.id %}">Détails enfant</a>
                    </div>   
            </div>
            {% endfor %}
          </div>
        </div>
      </div> 
    </div>
  </div>                            
</div>







 

App_AssMat/contrat/templates/contrat/remuneration_list.html
{% load static %}


<section class="section is-medium">
  <h1 class="title">Recap Remunerations</h1>
        <h2 class="subtitle">
          Recapitule tout <strong>les rémunérations.</strong>
        </h2>

        <table class="table is-bordered">
      
            <thead>
                <tr>
                    <th>base_mensuel</th>
                    <th>heure_mensuel</th>
                    <th>taux_h_brut</th>
                    <th>taux_h_net</th>
                    <th>jour_mensuel</th>
                    <th>contrat</th>
                    <th>Modifier congés</th>
                </tr>
            </thead>
            <tbody>
              {% for remuneration in remunerations %}
              <tr>
                <th>{{ remuneration.base_mensuel }}</th>
                <td>{{ remuneration.heure_mensuel }}</td>
                <td>{{ remuneration.taux_h_brut }}</td>
                <td>{{ remuneration.taux_h_net }}</td>
                <td>{{ remuneration.jour_mensuel }}</td>
                <td>{{ remuneration.contrat }}</td>
                <td><a class="button is-dark" href="" >Modifier congés</a> </td> 
              </tr>
              {% endfor %}
            </tbody>
        </table>
</section>