App_AssMat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('liste_employeurs/', include('famille.urls')),
    path('liste_contrats/', include('contrat.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/dashboard/urls.py
from django.urls import path
from django.urls.conf import include, include
from dashboard.views import index, Contrat_Vierge
from django.conf import settings
from django.conf.urls.static import static


app_name = 'dashboard'

urlpatterns = [
    path('', index, name='dashboard'),
    path('contrat_vierge/', Contrat_Vierge , name='contrat_vierge'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/famille/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from famille.views import (EmployeurView, 
                           EmployeurCreate, 
                           EmployeurDetail, 
                           EmployeurDeleteView, 
                           EmployeurUpdateView,
                           ContactUrgenceCreate,
                           ContactUrgenceView,
                           ContactUrgenceDetail,
                           ContactUrgenceUpdateView,
                           ContactUrgenceDeleteView,
                           )


# Create your views here.
app_name = 'famille'

urlpatterns = [
    path('', EmployeurView.as_view(), name='liste_employeurs'),
    path('creation_employeur/', EmployeurCreate.as_view(), name='creation_employeur'),
    path('<int:pk>/', EmployeurDetail.as_view(), name='details_employeur'),
    path('<int:pk>/edit/', EmployeurUpdateView.as_view(), name='editter_employeur'),
    path('<int:pk>/delete/', EmployeurDeleteView.as_view(), name='effacer_employeur'),
    path('<int:pk>/liste_contact_urgence/', ContactUrgenceView.as_view(), name='liste_contact_urgence'),
    path('<int:pk>/creation_contact_urgence/', ContactUrgenceCreate.as_view(), name='creation_contact_urgence'),
    # path('<int:pk>/liste_contact_urgence/<int:pk>/detail_urgence/', ContactUrgenceDetail.as_view(), name='detail_urgence'),
    path('liste_contact_urgence/<int:pk>/edit/', ContactUrgenceUpdateView.as_view(), name='edit_urgence'),
    path('liste_contact_urgence/<int:pk>/delete/', ContactUrgenceDeleteView.as_view(), name='effacer_urgence'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_AssMat/famille/models.py
from django.db import models
from django.urls import reverse
from account.models import CustomUser

# Create your models here.
class Employeur(models.Model):
    email = models.EmailField(max_length=40, blank=True, null=True)
    photo = models.ImageField(upload_to="photo_profil/", blank=True, null=True)
    nom = models.CharField(max_length=40, blank=True, null=True)
    prenom = models.CharField(max_length=20, blank=True, null=True)
    adresse_postale = models.CharField(max_length=40, blank=True, null=True)
    code_postal =models.CharField(max_length=5, blank=True, null=True)
    ville = models.CharField(max_length=40, blank=True, null=True)
    tel_fix = models.CharField(max_length=10, blank=True, null=True)
    tel_mob = models.CharField(max_length=10, blank=True, null=True)
    tel_doc = models.CharField(max_length=10, blank=True, null=True)
    date_anniv = models.DateTimeField(blank=True, null=True)
    num_urssaf = models.CharField(max_length=13, blank=True, null=True)
    ass_mat = models.ForeignKey(to=CustomUser, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Employeur"
        verbose_name_plural = "Employeurs"

    def __str__(self):
        return f"{self.nom} - {self.prenom}"
    
    # def get_absolute_url(self):
    #     return reverse('famille:famille')


class Famille(models.Model):
    pass

class ContactUrgence(models.Model):
    nom = models.CharField(max_length=40, blank=True, null=True)
    prenom = models.CharField(max_length=20, blank=True, null=True)
    filiation = models.CharField(max_length=20, blank=True, null=True)
    tel_fix = models.CharField(max_length=10, blank=True, null=True)
    tel_mob = models.CharField(max_length=10, blank=True, null=True)
    employeur = models.ForeignKey(to=Employeur, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Contact Urgence"
        verbose_name_plural = "Contacts Urgences"

    def __str__(self):
        return f"{self.nom} - {self.prenom}"

App_AssMat/famille/forms.py
from django import forms

from famille.models import Employeur, ContactUrgence

class NewEmployeurForm(forms.ModelForm):
    """"""
    class Meta:
        model = Employeur
        fields = ['nom', 
                  'prenom',
                  'email',
                  'photo',
                  'adresse_postale',
                  'code_postal',
                  'ville', 
                  'tel_fix', 
                  'tel_mob', 
                  'tel_doc', 
                  'date_anniv', 
                  'num_urssaf'
                  ]

        
class NewContactUrgenceForm(forms.ModelForm):
    """"""
    class Meta:
        model = ContactUrgence
        fields = ['nom', 
                  'prenom', 
                  'filiation', 
                  'tel_fix', 
                  'tel_mob', 
                  ]
        

App_AssMat/famille/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.urls import reverse

from famille.models import Employeur, ContactUrgence

from famille.forms import NewEmployeurForm, NewContactUrgenceForm


# Employeur class CRUD

class EmployeurView(ListView):
    model = Employeur
    #queryset = Employeur.objects.all()
    context_object_name = "employeurs"
    template_name = "famille/employeur_list.html"


class EmployeurCreate(CreateView):
       model = Employeur
       form_class = NewEmployeurForm
       template_name = "famille/employeur_create.html"
       success_url = '/dashboard/'
       
       def form_valid(self, form):
           form.instance.ass_mat = self.request.user
           return super().form_valid(form)
       

class EmployeurDetail(DetailView):
    model = Employeur
    template_name = "famille/employeur_details.html"
    context_object_name = "employeur"
    

class EmployeurUpdateView(UpdateView):
    model = Employeur
    form_class = NewEmployeurForm
    template_name = "famille/employeur_create.html"
    success_url = '/liste_employeurs/'
    

class EmployeurDeleteView(DeleteView):
    model = Employeur
    context_object_name = "employeur"
    template_name ='famille/employeur_delete.html'
    success_url = '/liste_employeurs/'


#Contact Urgence CRUD
   
class ContactUrgenceView(ListView):
    model = ContactUrgence
    context_object_name = "contacts_urgences"
    template_name ='famille/urgence_list.html'
    success_url = '/liste_employeurs/'
    
    def get_queryset(self):
        queryset = ContactUrgence.objects.filter(employeur=self.kwargs['pk'])
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) # get the default context data
        context['employeur_id'] = self.kwargs["pk"]
        return context


class ContactUrgenceDetail(DetailView):
    model = ContactUrgence
    context_object_name = "contacts_urgences"
    template_name ='famille/urgence_details.html'
    success_url = '/liste_employeurs/'
    

class ContactUrgenceCreate(CreateView):
    model = ContactUrgence
    form_class = NewContactUrgenceForm
    template_name ='famille/urgence_create.html'
    
    
    def form_valid(self, form):
        form.instance.employeur = Employeur.objects.get(id=self.kwargs["pk"])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("famille:liste_contact_urgence", kwargs={"pk": self.kwargs["pk"]})
    
class ContactUrgenceUpdateView(UpdateView):
    model = ContactUrgence
    form_class = NewContactUrgenceForm
    context_object_name = "contacts_urgences"
    template_name ='famille/urgence_create.html'
    
    
    def get_success_url(self):
        contact_urgence = ContactUrgence.objects.get(id=self.kwargs["pk"])
        employeur = Employeur.objects.get(id=contact_urgence.employeur.id)
        return reverse("famille:liste_contact_urgence", kwargs={"pk": employeur.id})
    
class ContactUrgenceDeleteView(DeleteView):
    model = ContactUrgence
    context_object_name = "contacts_urgences"
    template_name ='famille/urgence_delete.html'
    
    
    def get_success_url(self):
        contact_urgence = ContactUrgence.objects.get(id=self.kwargs["pk"])
        employeur = Employeur.objects.get(id=contact_urgence.employeur.id)
        return reverse("famille:liste_contact_urgence", kwargs={"pk": employeur.id})

App_AssMat/famille/templates/famille/employeur_create.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}
<form enctype="multipart/form-data" action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
                {{form.nom}}
            </div>
            <label class="label">Prénom:</label>
            <div class="control">
                {{form.prenom}}
            </div>
            <label class="label">Email:</label>
            <div class="control">
                {{form.email}}
            </div>
            <label class="label">Photo:</label>
            <div class="control">
                {{form.photo}}
            </div>
            <label class="label">Adresse:</label>
            <div class="control">
                {{form.adresse_postale}}
            </div>
            <label class="label">Code postal:</label>
            <div class="control">
                {{form.code_postal}}
            </div>
            <label class="label">Ville:</label>
            <div class="control">
                {{form.ville}}
            </div>
            <label class="label">Télephone fix:</label>
            <div class="control">
                {{form.tel_fix}}
            </div>
            <label class="label">Télephone mobile:</label>
            <div class="control">
                {{form.tel_mob}}
            </div>
            <label class="label">Télephone docteur:</label>
            <div class="control">
                {{form.tel_doc}}
            </div>
            <label class="label">Date d'anniversaire:</label>
            <div class="control">
                {{form.date_anniv}}
            </div>
            <label class="label">Numero Urssaf:</label>
            <div class="control">
                {{form.num_urssaf}}
            </div>
            
        </div>
    <input class="button is-dark" type="submit" value="Validez votre employeur"> 
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>          
</form>
{% endblock %}

App_AssMat/famille/templates/famille/employeur_delete.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}

<form action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
               <p>Voulez-vous supprimer cet employeur: {{ employeur.nom }} ? </p> 
            </div>
        </div>
    <input class="button is-dark" type="submit" value="Validez votre suppression employeur">     
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>      
</form>
{% endblock %}

App_AssMat/famille/templates/famille/employeur_details.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}



{% block content %}   
{% if employeur.photo %}
    <img src="{{ employeur.photo.url }}">
{% endif %}
    <div class="field has-text-centered">
        <label class="label">Nom:</label>
        <div class="control">
            {{employeur.nom}}
        </div>
        <label class="label">Prénom:</label>
        <div class="control">
            {{employeur.prenom}}
        </div>
        <label class="label">Email:</label>
        <div class="control">
            {{employeur.email}}
        </div>
        <label class="label">Adresse:</label>
        <div class="control">
            {{employeur.adresse_postale}}
        </div>
        <label class="label">Code postal:</label>
        <div class="control">
            {{employeur.code_postal}}
        </div>
        <label class="label">Ville:</label>
        <div class="control">
            {{employeur.ville}}
        </div>
        <label class="label">Télephone fix:</label>
        <div class="control">
            {{employeur.tel_fix}}
        </div>
        <label class="label">Télephone mobile:</label>
        <div class="control">
            {{employeur.tel_mob}}
        </div>
        <label class="label">Télephone docteur:</label>
        <div class="control">
            {{employeur.tel_doc}}
        </div>
        <label class="label">Date d'anniversaire:</label>
        <div class="control">
            {{employeur.date_anniv}}
        </div>
        <label class="label">Numero Urssaf:</label>
        <div class="control">
            {{employeur.num_urssaf}}
        </div>
        <br>
        <div>
            <a class="button is-dark" href="{% url 'famille:effacer_employeur' pk=employeur.id %}" >Effacer employeur</a> 
            <a class="button is-dark" href="{% url 'famille:editter_employeur' pk=employeur.id %}" >Modifier employeur</a> 
            <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>
        </div>
    </div>
    

{% endblock %}

App_AssMat/famille/templates/famille/employeur_list.html
{% load static %}

             
  <div class="card events-card">
    <header class="card-header">
      <p class="card-header-title">
        Récapitulatif informations employeurs
      </p>
      <a href="#" class="card-header-icon" aria-label="more options"></a>
    </header>
    <div class="card-table">
        <div class="content">
              <table class="table is-fullwidth is-striped">
                <tbody>
                  {% for employeur in employeurs %}
                  <tr>
                    <td><a href="{% url 'famille:details_employeur' pk=employeur.id %}" >{{ employeur.nom }}</a>
                    </td>
                    <td>{{ employeur.tel_fix }}</td>
                    
                    <td>{{ employeur.tel_mob }}</td>
                    <td>{{ employeur.tel_doc }}</td>
                    <td>{{ employeur.adresse_postale }}</td>
                    <td>{{ employeur.code_postal }}</td>
                    <td>{{ employeur.num_urssaf}}</td>
                    <td>{{ employeur.date_anniv }}</td>
                    <td>{{employeur.email}}</td>
                    <td><a class="button is-small is-primary" href="{% url 'famille:liste_contact_urgence' employeur.id %}" >Liste contacts urgence</a> </td> 
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
        </div>
    </div>                            
  </div>

App_AssMat/famille/templates/famille/urgence_create.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

{% block content %}
<div class="columns is-mobile is-multiline is-centered"> 
    <div class="column is-narrow">
        <p class="bd-notification is-primary">
            <h5 class="title is-5">Bonjour {{user.username}} , vous souhaitez créer un nouveau contact d'urgences pour "{{employeur.nom}}"</h5>
        </p>
    
        <form action="" method="POST" class="box">
            {% csrf_token %}
                <div class="field">
                    <label class="label">Nom:</label>
                    <div class="control">
                        {{form.nom}}
                    </div>
                    <label class="label">Prénom:</label>
                    <div class="control">
                        {{form.prenom}}
                    </div>
                    <label class="label">Filiation:</label>
                    <div class="control">
                        {{form.filiation}}
                    </div>
                    <label class="label">Télephone fix:</label>
                    <div class="control">
                        {{form.tel_fix}}
                    </div>
                    <label class="label">Télephone mobile:</label>
                    <div class="control">
                        {{form.tel_mob}}
                    </div>
                    
                </div>
            <input class="button is-dark" type="submit" value="Validez votre employeur"> 
            <a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>          
        </form>
    </div>
</div>
{% endblock %}

App_AssMat/famille/templates/famille/urgence_delete.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}
<form action="" method="POST" class="box">
    {% csrf_token %}
        <div class="field">
            <label class="label">Nom:</label>
            <div class="control">
               <p>Voulez-vous supprimer ce contact d'urgence: {{ contacts_urgences.nom }} ? </p> 
            </div>
        </div>
    <input class="validation" type="submit" value="Validez votre suppression contact urgence">     
    <a class="button is-dark" href="{% url 'dashboard:dashboard' %}" >Retour Liste employeur</a>      
</form>
{% endblock %}

App_AssMat/famille/templates/famille/urgence_details.html
{% extends "dashboard/base_dashboard_02.html" %}
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">

{% block content %}
<section class="section is-medium">
    <a class="button is-dark" href="{% url 'famille:liste_employeurs' %}" >Retour Liste employeur</a> 
    <a class="button is-dark" href="{% url 'famille:effacer_employeur' employeur.id %}" >Effacer employeur</a> 
    <a class="button is-dark" href="{% url 'famille:editter_employeur' employeur.id %}" >Modifier employeur</a> 
    <a class="button is-dark" href="{% url 'famille:creation_contact_urgence' %}" >Contacts d'urgence</a>
    <div class="field">
        <label class="label">Nom:</label>
        <div class="control">
            {{contacts_urgences.nom}}
        </div>
        <label class="label">Prénom:</label>
        <div class="control">
            {{contacts_urgences.prenom}}
        </div>
        <label class="label">Filiation:</label>
        <div class="control">
            {{contacts_urgences.filiation}}
        </div>
        <label class="label">Télephone fix:</label>
        <div class="control">
            {{contacts_urgences.tel_fix}}
        </div>
        <label class="label">Télephone mobile:</label>
        <div class="control">
            {{contacts_urgences.tel_mob}}
        </div>
        <label class="label">Employeur:</label>
        <div class="control">
            {{contacts_urgences.employeur}}
        </div>
    </div>
</section>
{% endblock %}

App_AssMat/famille/templates/famille/urgence_list.html
{% load static %}



{% block content %}

  <h1 class="title">Recap Contact d'urgences</h1>
        
        
  <table class="table">
      
      <thead>
          <tr>
              <!-- <th>ID</th> -->
              <th>Contacts d'urgences</th>
              <th>Prénom</th>
              <th>Tel_fix</th>
              <th>Tel_mobile</th>
              <th>Filiation</th>
              <!-- <th>Employeur</th> -->
              <th>Modifier</th>
              <th>Supprimer</th>
          </tr>
      </thead>
      <tbody>
        {% for contact_urgence in contacts_urgences %}
        <tr>
          <!-- <th>{{ contact_urgence.id }}</th> -->
          <td>{{ contact_urgence.nom }}</td>
          <td>{{ contact_urgence.prenom }}</td>
          <td>{{ contact_urgence.tel_fix }}</td>
          <td>{{ contact_urgence.tel_mob }}</td>
          <td>{{ contact_urgence.filiation }}</td>
          <!-- <td>{{ contact_urgence.employeur.nom }}</td> -->
          <td><a class="button is-dark is-small" href="{% url 'famille:edit_urgence' contact_urgence.id %}" >Modifier contacts urgences</a> </td>
          <td><a class="button is-dark is-small" href="{% url 'famille:effacer_urgence' contact_urgence.id %}" >Supprimer contacts urgences</a> </td>
          
        </tr>
        {% endfor %}
      </tbody>
  </table>

{% endblock %}

<a class="button is-dark" href="" >Creation Contacts d'urgence</a>
<a class="button is-dark" href="{% url 'dashboard:dashboard' %}">Retour tableau de bord</a>